### ISSUE TITLE
Fresh gvm install on Sierra 10.12.2 can't gvm install go1.7 without Sierra optimized go.

### ISSUE THREAD

**Issue by anthcor** [moovweb/gvm#250]
On a fresh install of Sierra 10.12.2 ...

```sh
xcode-select --install

# assuming you have home-brew installed without special setups
brew update
brew install mercurial

# using zsh, install gvm
zsh < <(curl -s -S -L https://raw.githubusercontent.com/moovweb/gvm/master/binscripts/gvm-installer)

# install go1.7
gvm install go1.7
```

So running that last `gvm install` throws all kinds of weird install errors. I tried installing lower versions of go via gvm to make up for this, but the only working solution I found was to `gvm implode`, `brew install go` (to ensure that the go I was installing was ready for Sierra), then reinstalling gvm and leaving that brew installed go as the "`system`" version.

**Comment by brendensoares** [comment]
I'm having similar issue building 1.6 on Sierra. I had 1.4 and 1.5 installed before upgrading. What kinds of errors are you seeing @anthcor ?

**Comment by brendensoares** [comment]
I can now compile via `gvm install go1.6` after switching `gvm use 1.5` and setting `export GOROOT_BOOTSTRAP=$GOROOT`. I was using go1.4 before and that was causing a `failed MSpanList_Insert` error.

**Comment by markeissler** [comment]
This is likely fixed by PR #233 which also adds a bunch of other things.

**Comment by anthcor** [comment]
@brendensoares yep i had the same issues. i'd suggest `gvm implode` and uninstalling any versions of `go` from your machine, then doing a fresh `brew install go` or download the latest `go` from wherever you please. once that's finished, reinstall `gvm`, and then proceed to install your desired version of `go` from `gvm`. 

@markeissler good looks! 😎

**Comment by osdiab** [comment]
for @anthcor 's solution, ensure that you also run `gvm use system` or it will still fail for the same reason :)

**Comment by markeissler** [comment]
@brendensoares @anthcor @osdiab [GVM2](https://github.com/markeissler/gvm2) is now in its first release. It should fix some of the problems people are having. If not, just open an issue there.
